name: Java Build and Folder Creation

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment for the job

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify the version of Java (adjust based on your needs)
          distribution: 'adoptopenjdk'

      - name: Build the project using Maven
        run: |
          # Run the build command (adjust if you're using Gradle or another build tool)
          mvn clean install

      - name: Create a folder in the desired location
        run: |
          # Create a folder on the system's Desktop (adjust for your OS)
          mkdir "C:\Users\OneDrive\Desktop\Content\BuildOutput"
          
          # Move the build output to the folder
          move target\* "C:\Users\OneDrive\Desktop\Content\BuildOutput"
        
        shell: pwsh  # Use PowerShell for Windows paths
