name: Java Build on Pull Request2

on:
  pull_request:
    branches:
      - main  # Trigger this workflow for pull requests targeting the main branch
 

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner to handle Windows paths

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Java JDK
        uses: actions/setup-java@v3  # Set up Java


      - name: Build the project using Maven
        run: 
          mvn clean install  # Adjust if you are using a different build tool like Gradle

      - name: Create a folder in the desired location
        run: 
          # Create a folder at the given path
          mkdir "C:\Users\OneDrive\Desktop\Content\PR-BuildOutput"
          
          
        
        shell: pwsh  # Use PowerShell for Windows paths
