name: Java Build on Pull Request2

on:
  pull_request:
    branches:
      - main  
 

jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3  

      - name: Set up Java JDK
        uses: actions/setup-java@v4.6.0
        with:  
         java-version: '17'
         distribution: 'oracle'
            


      - name: Build the project using Maven
        run: 
          mvn clean install 
      - name: Checkout orphan branch dev2
        run: |
          git config --global user.email a.narayanssm@gmail.com
          git config --global user.name Aishwaryendra01
          git checkout --orphan dev2
          git reset --hard   
      - name: Commit build artifacts
        run: |
          # Add the Maven build artifacts
          git add target/
          git commit -m "Add build artifacts from pull request"
          git push origin dev2 --force    
    
    
        
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          
        
        shell: pwsh  
